service: s3-textract

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource:
            - "arn:aws:s3:::20231113-image-bucket/*"
            - "arn:aws:s3:::20231113-text-bucket/*"
        - Effect: Allow
          Action:
            - textract:StartDocumentTextDetection
            - textract:GetDocumentTextDetection
          Resource:
            - "*"

functions:
  detectText:
    handler: handler.detectText
    timeout: 120
    events:
      - s3:
          bucket: 20231113-image-bucket
          event: s3:ObjectCreated:*
          existing: true
    layers:
      - {Ref: AwsLayerLambdaLayer}

resources:
  Resources:
    20231113ImageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: 20231113-image-bucket
    20231113TextBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: 20231113-text-bucket

layers:
  awsLayer:
    path: aws-layer